/**
 * One entry per Dashboard toggle (Moderation → Rules) in the app under test.
 * `message` is content that rule should block when ON and let through when OFF.
 * Messages carry a unique suffix so each run's evidence can be traced.
 */
export interface ToggleCase {
  code: string;
  ruleId: string;
  kind: 'text' | 'image' | 'video';
  /** Text to send, or file path for media. */
  message: (tag: string) => string;
  /** Why this toggle can't be executed, when it can't. */
  notRunReason?: string;
}

export const TOGGLE_CASES: ToggleCase[] = [
  { code: 'PROF', ruleId: 'profanity-filter', kind: 'text', message: (t) => `damn this is annoying ${t}` },
  { code: 'CONT', ruleId: 'contact_details_filter', kind: 'text', message: (t) => `call me on 9876543210 ${t}` },
  { code: 'EMAIL', ruleId: 'email_filter', kind: 'text', message: (t) => `mail me at qa.test@example.com ${t}` },
  // Custom rule: blocks the keyword list "customer_webhooks" = aman, OTP, hello.
  { code: 'CUST', ruleId: 'custome', kind: 'text', message: (t) => `hello, your OTP is ready ${t}` },
  {
    code: 'SPAM',
    ruleId: 'spam-detection',
    kind: 'text',
    message: (t) => `WIN BIG!!! Buy cheap followers now, 90% OFF, click here, limited offer, buy buy buy!!! ${t}`,
  },
  {
    code: 'SCAM',
    ruleId: 'scam-detection',
    kind: 'text',
    message: (t) => `Congratulations, you won a cash prize! Send your bank account details and a processing fee today to claim it. ${t}`,
  },
  {
    code: 'PLAT',
    ruleId: 'platform-circumvention',
    kind: 'text',
    message: (t) => `Let's move this conversation off this app, message me on WhatsApp or Telegram instead. ${t}`,
  },
  {
    code: 'TOX',
    ruleId: 'toxicity',
    kind: 'text',
    message: (t) => `You are a worthless, stupid idiot and nobody wants you here. ${t}`,
  },
  { code: 'IMG', ruleId: 'image-moderation', kind: 'image', message: () => 'fixtures/unsafe-revolver.jpg' },
  // 4s clip of the revolver photo, generated by scripts/make-unsafe-video.ts.
  { code: 'VID', ruleId: 'video-moderation', kind: 'video', message: () => 'fixtures/unsafe-revolver.mp4' },
];
